version: '3.8'


services:
  # Определяем сервис с именем python-app
  python-app:
    # Задаем путь к Dockerfile для сборки контейнера
    build: ./
    # Открываем порт 5535 на хосте и привязываем его к порту 5535 внутри контейнера
    ports:
      - "5535:5535"